name: CI/CD Pipeline for Psy Frontend App

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: psy-env
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node JS
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: npm install

      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker compose build

      - name: Push to Docker Hub
        run: docker compose push
